### ISSUE TITLE
Is  gsconfig_url undefined when try statement fails

### ISSUE THREAD

**Issue by Jarvx** [mitwelten/mitwelten-geo-backend#1]
https://github.com/mitwelten/mitwelten-geo-backend/blob/9b0b8f5ff0a984254357b71bbe0ffc8271722150/ogr2pg2gs.py#L155

Hi,

I was wondering if the try gives an exception, then the program seems to continue the flow until line 155 when the gsconfig_url is accessed as it is only defined when no exception happens.

**Comment by mlacayoemery** [comment]
Yes, you have understood correctly. That is a bit of a logic error on my part. I should re-raise the exception after logging.
